### ISSUE TITLE
Equities are sometimes sligthly off

### ISSUE THREAD

**Issue by pevas** [alberthendriks/lpokerbot#2]
Equities of hands are not always correct comparing to Equilab and Flopzilla, for both 5 and 7 card evaluation.

Example:
2h2s vs AsKh
Equilab & Flopzilla: 52.26%
Here: win: 900746; loss: 800379; draw: 11179; equity: 52.93% (calculated as ratio of wins and half of draws to the total)

Even without a tie possibility (after flop), result of this tool is off by around 0.5 - 1.5% from hands I've tested.

For some cases, like the included QQ vs AKo, the result is almost precise. I might be wrong in how I expect this to work, but I think that since there is no approximation anywhere, the results should be 100% equal to Equilab? Otherwise, really well done with how fast you managed to make it, it's super fast!

**Comment by pevas** [comment]
Postflop evaluations can lead to bigger differences, for example 8s8c vs KsJs on AsAc5d is 58.74%, should be 68.84%
```
System.out.println(rangeVsRange(new int[]{6, 6, 12, 12, 3, -1, -1, 11, 9}, new int[]{0, 1, 0, 1, 2, -1, -1, 0, 0}));
```
```
win: 580; loss: 407; draw: 3; equity: 58.737373
```

**Comment by alberthendriks** [comment]
@pevas Thanks for testing so thoroughly! After a deep dive in the code I found the issue and fixed it. That postflop situation is also handled correctly now. Can I assign this issue to you for validation?

**Comment by alberthendriks** [comment]
@pevas Whoops forgot to push, now done.

**Comment by pevas** [comment]
Verified it's giving much more accurate results now. There is still a tiny 0.05% difference but I guess this is just due to the imprecision of double and for all practical purposes it is negligible. Thanks for the fix!

**Comment by alberthendriks** [comment]
@pevas 0.05% should not be caused by double precision. In

**Comment by alberthendriks** [comment]
@pevas 0.05% should not be caused by double precision. Do you have an example situation? I added an equity print statement (are you sure? I get 0.05% off the flop situation when I (wrongly) use integer division on draws (`draw/2` inside a statement rounds down)).

**Comment by pevas** [comment]
It is possible that it is some embarassing mistake on my side :) This is how I calculate the equity:
`(100 * (win + draw / (double) 2)) / ((double) win + draw + loss)`

As an example, the hand from my second comment (88 vs KJ on AA5), I get '68.89564336372847' whereas Equilab says '68.84'

**Comment by alberthendriks** [comment]
That seems correct, I can replace my code in the last commit above (3090501) with that statement, and when I use that on 

    rangeVsRange(new int[]{6, 6, 12, 12, 3, -1, -1, 11, 9}, new int[]{0, 1, 0, 1, 2, -1, -1, 0, 0})

I still get: 68.83838383838383, not 68.89564336372847

**Comment by pevas** [comment]
I am unable to get my original result so I must have done something wrong originally. Getting the right result now.
