### ISSUE TITLE
'int[] cards' class variable causes race conditions

### ISSUE THREAD

**Issue by pevas** [alberthendriks/lpokerbot#3]
I thought I might as well point this out too. Declaring the variable below as a class variable causes issues when multiple threads are using the calculation, leading to unpredictable results. While you don't promise the calculation is supposed to be thread safe, moving `cards` to a local variable inside the `rankPokerHand7()` method (it's the only method that uses it) fixed the thread safety issues in my tests, so it might be worth applying such a fix in case you or other users are using it concurrently.
https://github.com/alberthendriks/lpokerbot/blob/a5684e84b227d3e1e9494d659518840cfb98feda/RankPokerHandPublic.java#L168

**Comment by alberthendriks** [comment]
Yes, that's true. In tests with early versions I found that the algorithm was a bit faster when placing that variable in the class instead of the method, but I don't remember why. I'll check this next time.

**Comment by alberthendriks** [comment]
Thanks for pointing that out. The array should not be initialized in `rankPokerHand7()` for performance reasons (It is the critical method and it has no `new`-initialization). I found a solution to make the application thread-safe by passing it as a parameter instead. It's ugly, but in this case it's performance over readability.
The current change may even make things faster.

**Comment by pevas** [comment]
Looks good from my tests, thanks.
